baseURL = "https://keithyipkw.github.io/blog/"

title = "STEM"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 5
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false
publishDir = "docs"

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts"]
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "dark"

[params.brand]
domain = "domain"
email = "email"

[params.social]
facebook = ""
github = ""
instagram = ""
linkedin = ""
pinterest = ""
stackoverflow = ""
twitter = ""
youtube = ""
footer = []

[params.services]
googleAnalyticsId = "G-5Y5GJS2SYG"
googleTagManagerId = ""
googleAdsId = ""
googleAdsenseId = ""
googleAdsenseAdSlotId = ""
googleAdsenseLoad = ""
googleAdsConversionId = ""
googleAdsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.logo]
inline = false
path = "image/brand/logo.png"

[params.image]
width = "2048"
height = "1024"
faviconIco = "favicon.ico"
faviconAlt = "image/brand/favicon.png"
icon1To1 = "image/brand/icon-1-1.png"
icon2To1 = "image/brand/icon-2-1.png"
default = ""

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = ""
version = ""
image = ""
raw = ""
video = ""

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[[menu.foot]]
url = "about/"
name = "About"
weight = 2

[[menu.foot]]
url = "copyright/"
name = "Copyright"
weight = 3

[languages]
[languages."en"]
weight = 1
languageName = "English"
